spring:
  application:
    name: cloud-ecommerce-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_ecommerce_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}